### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by limelect** [benibela/apim#1]
lazarus 1.6.4
compile error

windowfuncs.pas(494,1) Error: Unrecognized opcode dw
windowfuncs.pas(494,4) Error: Assembler syntax error
windowfuncs.pas(495,15) Error: Unknown identifier "EAX"
windowfuncs.pas(495,15) Error: Size suffix and destination or source size do not match
windowfuncs.pas(496,16) Error: Unknown identifier "EDX"
windowfuncs.pas(496,16) Error: Size suffix and destination or source size do not match
windowfuncs.pas(500,1) Error: Unrecognized opcode dw
windowfuncs.pas(500,4) Error: Assembler syntax error
windowfuncs.pas(501,5) Error: Unknown identifier "EAX"
windowfuncs.pas(502,5) Error: Unknown identifier "EDX"
windowfuncs.pas(503,15) Error: Unknown identifier "EAX"
windowfuncs.pas(503,15) Error: Size suffix and destination or source size do not match
windowfuncs.pas(504,16) Error: Unknown identifier "EDX"
windowfuncs.pas(504,16) Error: Size suffix and destination or source size do not match

I have added {$asmmode intel}   

NO LDockCtrl any more !!!

**Comment by benibela** [comment]
Are you compiling for 64-bit Windows? That function is for 32-bit


>NO LDockCtrl any more !!!

So many changes

I had not looked at the docking classes in years

**Comment by limelect** [comment]
Compiling for 32 bit

**Comment by benibela** [comment]
After removing LDockCtrl nothing works anymore in WINE. But I do not have access to a Windows system atm

>Compiling for 32 bit

Are you sure? Which fpc version do you have?

**Comment by limelect** [comment]
lazarus 1.6.4
fpc  3.0.2
SVN revision 54278
 removing LDockCtrl makes error

  public
    { Public-Deklarationen}
    //ControlDocker1: TLazControlDocker;
    DockingManager: TLazDockingManager;

**Comment by benibela** [comment]
Now it compiles and runs (except for some incompletely painted panels) with Lazarus 1.8 RC4 and fpc r35800
