### ISSUE TITLE
Binaries from home page immediately close after start with no GUI

### ISSUE THREAD

**Issue by roman-orekhov** [benibela/apim#2]
Hello!

This happens with the version available [here](https://www.benibela.de/tools_en.html#apim). The oldest file in that archive is from 23.10.08. Could you please update it with the version compiled for #1 ?

I'm not sure what could be the reason for it not starting properly. No errors, dumps, eventlog clear, same behavior when run in Windows XP mode. 4k monitor as reason?.. System is Windows 10 22H2 19045.3930

**Comment by benibela** [comment]
On my new Windows laptop, it fails to get a language code to load the translations

For some reason the fallback language code is `zz`

You can try to rename `apim.en.po` to `apim.zz.po`

>Could you please update it with the version compiled for https://github.com/benibela/apim/issues/1 ?

That was for compiling with a new Lazarus version. I am not sure compiling it with a new Lazarus won't break more than it fixes

**Comment by roman-orekhov** [comment]
> You can try to rename `apim.en.po` to `apim.zz.po`

That didn't fix the problem

**Comment by benibela** [comment]
You could use Procmon (https://learn.microsoft.com/de-de/sysinternals/downloads/procmon) to see what it is doing before stopping (ProcessExit)

![procmon](https://github.com/benibela/apim/assets/1205129/71a33180-b089-4b9e-8369-70cadaf52cf7)

**Comment by roman-orekhov** [comment]
Thanks, I had to provide `apim.ru.po` for it, so it ran!

Unfortunately it doesn't show responses to `SendMessage` (for e.g. `LB_GETCOUNT` (395))

**Comment by benibela** [comment]
>Unfortunately it doesn't show responses to SendMessage (for e.g. LB_GETCOUNT (395))

But it was supposed to: https://github.com/benibela/apim/commit/bf84e7b7e6cfb5a37ee49fcb0e0b4140623d1598#diff-6ccd64608eefdc84ee6189f1a58ba87a4b85e1e80104d0e7caf7024598541c55L265-L267

Well, I added that in 2009. Perhaps that is a reason to make new binaries after all
